### ISSUE TITLE
Kernel memory limit is unsupported on Linux kenrel >= 5.16

### ISSUE THREAD

**Issue by dubek** [kata-containers/cgroups-rs#81]
**Describe the bug**

As described first in https://github.com/kata-containers/kata-containers/issues/4390 , Linux 5.16 merged [a change](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=58056f77502) which causes writes to cgroup's `memory.kmem.limit_in_bytes` to return `-ENOTSUPP` and do nothing.

This means that the unit tests fail with Linux 5.16 *and* cgroup v1.

To reproduce this, I installed an Ubuntu 22.04 VM (default kernel 5.15). I added `systemd.unified_cgroup_hierarchy=0` to the kernel command-line. On 5.15 `make test` passes OK.

I then installed kernel 5.16.20 from Ubuntu ([link](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.16.20/amd64)). When I run the tests:

```
     Running tests/builder.rs (target/debug/deps/builder-4ff582e8201f8686)

running 7 tests
test test_blkio_res_build ... ignored
test test_devices_res_build ... ignored
thread 'test_memory_res_build' panicked at 'assertion failed: `(left == right)`
  left: `9223372036854771712`,
 right: `134217728`', tests/builder.rs:50:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test test_memory_res_build ... FAILED
test test_network_res_build ... ok
test test_cpu_res_build ... ok
test test_hugepages_res_build ... ok
test test_pid_res_build ... ok

failures:

failures:
    test_memory_res_build

test result: FAILED. 4 passed; 1 failed; 2 ignored; 0 measured; 0 filtered out; finished in 0.07s
```

**Expected behavior**
Unit tests pass.

It's a design question of whether to "swallow" the unsupported error from the OS and just do nothing, or keep the error (and fix the callers, such as kata agent). This is also related to the question in #76.

**Additional context**

1. With cgroup v2 this doesn't happen because the tests skip this.
2. I added a new test which attempts to call `set_kmem_limit` -- this indeed fails with OS error (95 unsupported).

**Comment by liubin** [comment]
Thank you @dubek , are you ready to fix this?

**Comment by wainersm** [comment]
Hi @dubek , @liubin , the fix for this issue is needed to enable a CI job for AMD SEV, so my interest on this.

I'm not an expert on this area but I'd like to share my opinion on the solutions raised by @dubek:
 * as a short term solution, it should always try to set kmem limit and ignore if Unsupported error. If possible also log a warning message saying the operation is no longer supported. 
 * In long term, just like the kernel, we should deprecate & remove it after a few releases. Use https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-deprecated-attribute to deprecate it.

**Comment by dubek** [comment]
I submitted PR #82 as a possible fix for this issue, according to the short term suggestion from @wainersm .
